Warning: batch size is bigger than the data size. Setting batch size to data size
100%|█████████████████████████████████████████████| 1/1 [00:01<00:00,  1.01s/it]
Warning: batch size is bigger than the data size. Setting batch size to data size
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/cocochamba/Python_labs/genai_food101_repo/train.py", line 26, in <module>
    trainer.training_loop()
  File "/home/cocochamba/Python_labs/genai_food101_repo/training/trainers/base_trainer.py", line 117, in training_loop
    val_metrics_dict, images, labels = self.validate()
                                      ^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/Python_labs/genai_food101_repo/training/trainers/base_trainer.py", line 153, in validate
    metrics_dict[metric.get_name()] = metric(
                                      ^^^^^^^
  File "/home/cocochamba/Python_labs/genai_food101_repo/metrics/metrics.py", line 11, in __call__
    fid = calculate_fid_given_paths(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/pytorch_fid/fid_score.py", line 261, in calculate_fid_given_paths
    m2, s2 = compute_statistics_of_path(paths[1], model, batch_size,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/pytorch_fid/fid_score.py", line 243, in compute_statistics_of_path
    m, s = calculate_activation_statistics(files, model, batch_size,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/pytorch_fid/fid_score.py", line 228, in calculate_activation_statistics
    act = get_activations(files, model, batch_size, dims, device, num_workers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/pytorch_fid/fid_score.py", line 132, in get_activations
    for batch in tqdm(dataloader):
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/_utils/collate.py", line 398, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/_utils/collate.py", line 155, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cocochamba/.pyenv/versions/neural/lib/python3.12/site-packages/torch/utils/data/_utils/collate.py", line 272, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: stack expects each tensor to be equal size, but got [3, 28, 28] at entry 0 and [3, 64, 64] at entry 8
